[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "OpenDriveVLA"
platforms = ["linux-64"]

[system-requirements]
cuda = "12.1"

[activation.env]
MMCV_WITH_OPS="1"

[dependencies]
#os dependencies like cuda etc
python = "3.10.*" #">3.8,<3.10" 
ninja = "*"
packaging = "*"
compilers = "*" #gets gcc, or gcc = "*"
gcc = ">=5"
setuptools = "*" #">=61.0"
cuda-nvcc = "12.1.*"
    #need cusparse.h, cublas.h, and cusolverDn.h for mmcv build
    #mp versions might not be needed
#cudatoolkit = "*"      #version conflict with cuda-nvcc
#cudatoolkit-dev = "*"  #doesn't have cusparse.h etc
cusparselt-dev = "*"
libcusparse-dev = "*"
libcublasmp-dev	= "*"
libcublas-dev = "*"	
libcusolvermp-dev = "*"
libcusolver-dev = "*"
psutil = "*"
libgl-devel = "*"
libgfortran = "*"
pip = "*"

[pypi-options]
no-build-isolation = ["mmcv-full", "mmdet3d"]

[pypi-dependencies]
#llava-torch = "==1.2.2.post1"
numpy = "==1.26.1"
torch = { version = "==2.1.2", index = "https://download.pytorch.org/whl/cu121" } #need long form with version and index that uses cu12
OpenDriveVLA = { path = ".", extras = ["train"] }
#flash-attn = "==2.5.7" #original wanted 2.5.7
#mmcv-full = {url = "https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/mmcv_full-1.7.2-cp39-cp39-manylinux1_x86_64.whl"}
#mmcv = ">=2.0.0rc4, <2.1.0" #original wanted local thirdparty/mmcv

#mmcv-full = {path = "third_party/mmcv_1_7_2", extras = ["all"]} #, extras = ["optional"]

mmdet = "==2.26.0" 
mmsegmentation = "==0.29.1"  
mmengine = "==0.9.0"
motmetrics= "==1.4.0" 
casadi = "==3.6.0"
scipy = "==1.10.1" 
scikit-image = "==0.19.3"
fsspec = "*"
triton = "*"
shapely = "==1.8.5.post1"
#mmdet3d = "==1.0.0rc6" #original wanted local thirdparty/mmdet3d

#mmdet3d = {path = "third_party/mmdetection3d_1_0_0rc6"}

#at mmdet3d 1.1.0 need mmcv>=2.0.0rc4, <2.1.0., with mmcv >=2.0.0rc4, <2.1.0. Error: No module named 'mmcv.runner'
#at mmdet3d 1.0.0rc6 need mmcv>=1.5.2, <=1.7.0, with mmcv-full 1.7.0 Error: No module named 'mmcv._ext'

#torch = "==2.1.2"

#transformers = "==4.54.1" #original wanted specific git version
#llava = {path = "<path in repo>"}

#mmcv-full = {path = "third_party/mmcv_1_7_2", extras = ["all"]}
#mmdet3d = {path = "third_party/mmdetection3d_1_0_0rc6"}