"""
Build NuX val entries in the LLaVANuScenesDataset-expected schema, with
the exact Stage 2 prompt so the trained VLA sees a familiar input.

Mirrors `stage2_convertor.convert_nux` but:
  - reads the VAL captions (data/nuX/Nu_X_val.json) instead of train.
  - points `uniad_pth` at data/fusionad_results_for_vlm/val/<token>.pth.
    Required so inference can use `--use-uniad-pth` -> turns off
    in_nuscenes_order dedup in the dataset and keeps ALL ~6019 entries.
  - carries top-level sidecar metadata (gt_answer, gt_narration,
    gt_reasoning, sample_token, question) for the post-inference scorer.

Prereq: data/fusionad_results_for_vlm/val/<token>.pth must already exist
(generated by pickle_fusionad_pth.py --nuscenes_set val).

Output: data/stage2_val_nux/val_nux.json
"""

import os
import sys
import json
import pickle
import argparse

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from tqdm import tqdm

from drivevla.data_converter.fusionad_converter.stage2_convertor import (
    generate_ego_and_history,
    build_human_turn,
    build_available_pth_set,
    CACHED_NUSCENES_PKL,
)

VAL_NUX_PATH         = "data/nuX/Nu_X_val.json"
FUSIONAD_PTH_DIR_VAL = "data/fusionad_results_for_vlm/val"

NUX_QUESTION = "Please provide a narration and reasoning for the current driving behavior."


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', default='data/stage2_val_nux/val_nux.json')
    parser.add_argument('--val_nux', default=VAL_NUX_PATH)
    parser.add_argument('--cached', default=CACHED_NUSCENES_PKL)
    parser.add_argument('--pth_dir', default=FUSIONAD_PTH_DIR_VAL)
    args = parser.parse_args()

    os.makedirs(os.path.dirname(args.output), exist_ok=True)

    print(f"Loading cached NuScenes info from {args.cached} ...")
    with open(args.cached, 'rb') as f:
        cached = pickle.load(f)

    print(f"Scanning available val pths in {args.pth_dir} ...")
    if not os.path.isdir(args.pth_dir):
        raise SystemExit(
            f"ERROR: {args.pth_dir} does not exist. Run "
            f"'pickle_fusionad_pth.py --nuscenes_set val' first."
        )
    available = build_available_pth_set(args.pth_dir)
    print(f"  {len(available)} val pths found")

    print(f"Loading val NuX from {args.val_nux} ...")
    with open(args.val_nux) as f:
        nux_data = json.load(f)

    entries = []
    skipped_no_cache = 0
    skipped_no_pth = 0
    for token, val in tqdm(nux_data.items(), desc='[NuX val]'):
        if token not in cached:
            skipped_no_cache += 1
            continue
        if token not in available:
            skipped_no_pth += 1
            continue

        narration = val['narration']
        reasoning = val['reasoning']
        gt_answer = f"Narration: {narration}\nReasoning: {reasoning}."

        ego_msg, his_msg = generate_ego_and_history(cached[token])
        human_turn = build_human_turn(ego_msg, his_msg, NUX_QUESTION)

        entries.append({
            "id": f"{token}_nux",
            "uniad_pth": os.path.join(args.pth_dir, f"{token}.pth"),
            "conversations": [
                {"from": "human", "value": human_turn},
                {"from": "gpt",   "value": gt_answer},
            ],
            "gt_answer":     gt_answer,
            "gt_narration":  narration,
            "gt_reasoning":  reasoning,
            "sample_token":  token,
            "question":      NUX_QUESTION,
        })

    print(f"[NuX val] {len(entries)} entries "
          f"({skipped_no_cache} no-cache, {skipped_no_pth} no-pth skipped)")

    with open(args.output, 'w') as f:
        json.dump(entries, f, indent=2)
    print(f"Saved -> {args.output}")


if __name__ == '__main__':
    main()
